#!/bin/bash

## Copyright (C) 2026 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

source /usr/libexec/helper-scripts/check_runtime.bsh || true
if ! declare -F was_executed >/dev/null; then
  printf '%s\n' "$0: ERROR: cannot source check_runtime.bsh!" >&2
  exit 1
fi

if was_sourced "${BASH_SOURCE[0]}"; then
  die 1 "Do not source this script!"
fi

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

"${MYDIR}/build_core" --windows
